[project]
name = "twscrape_api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "twscrape>=0.16.0",
]

[project.optional-dependencies]
api = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.0",
]
